apiVersion: v1
kind: Service
metadata: 
  name: simple-app-service
spec:
  selector:
    name: simple-app
  type: LoadBalancer
  # type: NodePort
  ports:
    - port: 7000
      targetPort: 5000
      # nodePort: 30002

      # NodePort => http://localhost:30002 for development
      # LoadBalancer => http://localhost:7000 for production